#!/usr/bin/env bash
set -euo pipefail

# Deploy the local grammar + queries to Zed as a dev extension (zed/).
#
# Zed only loads grammars from a git repo at a pinned rev (it compiles the
# WASM itself from src/), so this script auto-commits the current sources
# into a throwaway mirror repo (zed/.mirror) and points zed/extension.toml
# at the new commit. Your real repo history is never touched.
#
# First time:  in Zed run "zed: install dev extension" and pick the zed/ dir.
# After that:  run this script, then hit the "Rebuild" button on the
#              extension in Zed's Extensions panel (or reinstall it).

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXT_DIR="$REPO_DIR/zed"
MIRROR="$EXT_DIR/.mirror"

# --- Generate parser.c if the grammar changed ---
if [ "$REPO_DIR/src/parser.c" -nt "$REPO_DIR/grammar.js" ]; then
    echo "Skipping parser generation (grammar unchanged)..."
else
    echo "Generating parser..."
    tree-sitter generate "$REPO_DIR/grammar.js"
fi

# --- Sync queries into the extension ---
# Zed-specific queries live in queries/zed/ (adapted capture names) and take
# precedence; the Helix ones are the fallback where the two dialects agree.
# indents.scm never falls back: Helix indent captures (@indent/@outdent/
# @extend) don't mean the same thing in Zed. rainbows/tags are Helix-only.
echo "Syncing queries..."
for q in highlights injections locals textobjects indents overrides; do
    if [ -f "$REPO_DIR/queries/zed/$q.scm" ]; then
        cp "$REPO_DIR/queries/zed/$q.scm" "$EXT_DIR/languages/fsharp/$q.scm"
    elif [ "$q" != indents ] && [ -f "$REPO_DIR/queries/$q.scm" ]; then
        cp "$REPO_DIR/queries/$q.scm" "$EXT_DIR/languages/fsharp/$q.scm"
    fi
done

# --- Commit grammar sources into the mirror repo ---
if [ ! -d "$MIRROR/.git" ]; then
    echo "Creating grammar mirror repo..."
    git init -q "$MIRROR"
    # Let Zed fetch an arbitrary SHA over the file:// transport.
    git -C "$MIRROR" config uploadpack.allowAnySHA1InWant true
fi

cp "$REPO_DIR/grammar.js" "$MIRROR/grammar.js"
rm -rf "$MIRROR/src"
cp -r "$REPO_DIR/src" "$MIRROR/src"

git -C "$MIRROR" add -A
if ! git -C "$MIRROR" rev-parse -q --verify HEAD >/dev/null || \
   ! git -C "$MIRROR" diff --cached --quiet; then
    git -C "$MIRROR" \
        -c user.name="dev-zed" -c user.email="dev-zed@localhost" \
        commit -qm "sync $(date -Iseconds)"
    echo "Mirror updated."
else
    echo "Mirror already up to date."
fi
SHA="$(git -C "$MIRROR" rev-parse HEAD)"

# --- Write the extension manifest pointing at the new commit ---
cat > "$EXT_DIR/extension.toml" <<EOF
# Generated by dev-zed.sh — do not edit.

id = "fsharp"
name = "F# (local dev)"
version = "0.0.1"
schema_version = 1
description = "Local development build of tree-sitter-fsharp-helix"
repository = "https://github.com/MangelMaxime/tree-sitter-fsharp-helix"
authors = ["Maxime Mangel <me@mangelmaxime.fr>"]
languages = ["languages/fsharp"]

[grammars.fsharp]
repository = "file://$MIRROR"
rev = "$SHA"

[language_servers.fsautocomplete]
name = "FsAutoComplete"
languages = ["FSharp"]
EOF
echo "extension.toml -> rev $SHA"

# --- Rust wasm target (Zed compiles zed/src/lib.rs — the LSP glue — itself) ---
if command -v rustc >/dev/null 2>&1 && \
   ! ls "$(rustc --print sysroot)/lib/rustlib" 2>/dev/null | grep -q '^wasm32-wasip2$'; then
    echo "WARNING: Rust target wasm32-wasip2 not installed — Zed can't build the"
    echo "         LSP glue (pacman -S rust-wasm, or rustup target add wasm32-wasip2)."
fi

# --- Drop the stale compiled grammar so Zed can't reuse it ---
rm -f "$EXT_DIR/grammars/fsharp.wasm"

echo "Done."
echo
if [ -e "$HOME/.local/share/zed/extensions/installed/fsharp" ] && \
   [ ! -L "$HOME/.local/share/zed/extensions/installed/fsharp" ]; then
    echo "NOTE: the marketplace F# extension is installed; the dev extension"
    echo "(same id) overrides it once installed as a dev extension."
fi
echo "In Zed: Extensions panel -> Rebuild (first time: 'zed: install dev extension' -> $EXT_DIR)"
