; GENERATED by `./build.sh derive-queries` from ../folds.scm - do not edit.
; The patterns of the F# query that compile against the signature grammar.

; Consecutive line comments and `///` doc blocks fold as one region.
(line_comment)+ @fold
(xml_doc_comment)+ @fold
