; GENERATED by `./build.sh derive-queries` from ../indents.scm - do not edit.
; The patterns of the F# query that compile against the signature grammar.

; ── Control flow ──────────────────────────────────────────────────────────────
; `match` itself is not indented: F# style aligns `|` with `match`; the body
; of each arm (after `->`) is, via match_arm.
[
  (if_expression)
  (try_expression)
  (for_expression)
  (while_expression)
  (ce_match_bang_expr)
  (match_arm)
] @indent.begin

; ── Type-level declarations ───────────────────────────────────────────────────
; Only when the declaration opens a body (`type T =`), not `type kg`.
((type_decl "=") @indent.begin)
((type_and_decl "=") @indent.begin)
(type_extension) @indent.begin

[
  (record_type_defn)
  (anonymous_record_type)
  (struct_type_defn)
  (class_type_defn)
  (interface_type_defn)
] @indent.begin

; `module Foo =` opens a nested body; `module Foo.Bar` (file-scoped) does not.
((module_decl "=") @indent.begin)

; ── Delimited bodies ──────────────────────────────────────────────────────────
[
  (record_expression)
  (anonymous_record_expression)
  (list_expression)
  (array_expression)
  (object_expression)
  (computation_expression)
  (parenthesized_expression)
  (parenthesized_type)
  (begin_end_expression)
  (tuple_params)
  (tuple_pattern)
  (tuple_expression)
] @indent.begin

; ── Lines that start at the parent's level ────────────────────────────────────
[
  "else"
  "elif"
] @indent.branch

[
  ")"
  "]"
  "}"
  "|]"
  "|}"
  "end"
] @indent.branch

; ── Free-form text: never re-indent ──────────────────────────────────────────
[
  (string_literal)
  (verbatim_string)
  (triple_quoted_string)
  (multidollar_string)
  (line_comment)
  (xml_doc_comment)
  (block_comment)
  (block_doc_comment)
] @indent.auto
