; GENERATED by `./build.sh derive-queries` from ../textobjects.scm - do not edit.
; The patterns of the F# query that compile against the signature grammar.

; Neovim text objects (nvim-treesitter-textobjects capture names: `.outer` is
; the whole construct, `.inner` its body). The function/class/parameter/comment
; objects mirror ../textobjects.scm (Helix's `.around`/`.inside`); the rest are
; Neovim-only objects Helix has no keys for.

; ── Functions ────────────────────────────────────────────────────────────────
(let_binding body: (_) @function.inner) @function.outer
(let_decl_indented body: (_) @function.inner) @function.outer
(let_and_binding body: (_) @function.inner) @function.outer
(member_defn body: (_) @function.inner) @function.outer
(abstract_member_defn) @function.outer
(lambda_expression body: (_) @function.inner) @function.outer
(function_expression) @function.outer

; ── Types ────────────────────────────────────────────────────────────────────
(type_decl "=" . (_) @class.inner) @class.outer
(type_and_decl "=" . (_) @class.inner) @class.outer
(type_extension) @class.outer
(exception_decl) @class.outer
(class_type_defn) @class.outer
(struct_type_defn) @class.outer
(interface_type_defn) @class.outer
(module_decl) @class.outer

; ── Parameters and arguments ─────────────────────────────────────────────────
(parameter) @parameter.inner @parameter.outer
(tuple_param) @parameter.inner @parameter.outer
(tuple_expression (_) @parameter.inner @parameter.outer)

; ── Calls, blocks, control flow ──────────────────────────────────────────────
(application_expression) @call.outer

(computation_expression) @block.outer
(begin_end_expression) @block.outer
(parenthesized_expression) @block.outer

(if_expression) @conditional.outer
(if_expression else: (_) @conditional.inner)
(match_expression) @conditional.outer
(match_arm body: (_) @conditional.inner)
(try_expression) @conditional.outer

(for_expression body: (_) @loop.inner) @loop.outer
(while_expression body: (_) @loop.inner) @loop.outer

; ── Bindings, attributes, comments, numbers ──────────────────────────────────
(let_binding
  name: (_) @assignment.lhs
  body: (_) @assignment.rhs) @assignment.outer @assignment.inner
(let_decl_indented
  name: (_) @assignment.lhs
  body: (_) @assignment.rhs) @assignment.outer @assignment.inner

(attribute) @attribute.outer
(attribute (attribute_target) @attribute.inner)

[
  (line_comment)
  (xml_doc_comment)
  (block_comment)
  (block_doc_comment)
] @comment.outer @comment.inner

[
  (int_literal)
  (float_literal)
] @number.inner
