; GENERATED by `./build.sh derive-queries` from ../injections.scm - do not edit.
; The patterns of the F# query that compile against the signature grammar.

; Keep the shared rules in sync with zed/injections.scm (same syntax; it only
; adds Zed-specific extras).

((block_doc_comment) @injection.content
 (#set! injection.language "markdown"))

((xml_doc_comment) @injection.content
 (#set! injection.language "xml")
 (#set! injection.combined))

; TODO:/FIXME: markers through Helix's built-in `comment` grammar (the same
; injection Helix's own Rust queries use). Doc comments are excluded: they
; already inject markdown/xml.
([
  (line_comment)
  (block_comment)
] @injection.content
 (#set! injection.language "comment"))
