; GENERATED by `task queries:derive` from ../brackets.scm - do not edit.
; The patterns of the F# query that compile against the signature grammar.

("(" @open ")" @close)
("[" @open "]" @close)
("{" @open "}" @close)
("[|" @open "|]" @close)
("{|" @open "|}" @close)
("[<" @open ">]" @close)
("<@" @open "@>" @close)
("<@@" @open "@@>" @close)
("begin" @open "end" @close)
