#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.9"
# dependencies = ["tree-sitter>=0.25,<0.27"]
# ///
"""Four-axis scoreboard. Makes "is this grammar better?" a fact, not an argument.

    ./scripts/score.py                      # our parser, all axes
    ./scripts/score.py --vs /path/other.so  # side by side with another grammar
    ./scripts/score.py --json               # machine readable
    ./scripts/score.py --compare            # gate against test/score/baseline.json

Why four axes and not one clean-parse percentage:

  coverage   Valid F# must parse without error sites. Every repo in
             scripts/bench-manifest.txt is a COMPILING project, so a new error
             site there is always a coverage regression - never "honest
             rejection". Zero tolerance.

  rejection  Invalid F# should be flagged. Scored as two numbers, never one:
             recall on files whose expected diagnostic is a SYNTAX error, and
             the false-positive rate on files expecting only TYPE/name errors.
             A single "catch rate" rewards being broken, because rejecting
             syntactically valid code inflates it.

  degeneracy Counts reserved keywords lexed as `identifier` in files that have
             ZERO error sites - wrong trees that no error count can see. This is
             the counter-metric: it cannot be gamed by making files error out,
             so an honest clean-rate drop stays legible next to it.

  highlight  Fraction of capture names in queries/highlights.scm that any
             test/highlight assertion actually pins.

Corpora are frozen path lists under test/score/, generated by --regen-corpora
from the dotnet/fsharp checkout that bench.py already clones. Freezing means a
manifest SHA bump can never silently move a denominator.
"""

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import tsparse
from bench import BENCH_DIR, read_manifest, ensure_clones, list_files

REPO = Path(__file__).resolve().parent.parent
SCORE_DIR = REPO / "test" / "score"
BASELINE = SCORE_DIR / "baseline.json"
KEYWORDS = SCORE_DIR / "keywords.txt"

# F# diagnostics that are genuinely syntactic - the only ones a parser can be
# asked to catch. Everything else in the conformance suite is a type or
# name-resolution error that a correct parser must accept.
SYNTAX_DIAGNOSTICS = {"FS0010", "FS0058", "FS1156", "FS0583", "FS0584",
                      "FS0035", "FS0025", "FS0515", "FS3360"}
EXPECTS_RE = re.compile(r'id="?(FS\d+)')


def load_keywords():
    hard = []
    for line in KEYWORDS.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            hard.append(line)
    return {k.encode() for k in hard}


def read_list(name):
    path = SCORE_DIR / name
    if not path.exists():
        return None
    return [l for l in path.read_text().splitlines() if l and not l.startswith("#")]


def regen_corpora():
    """Classify dotnet/fsharp's test tree once, into frozen lists."""
    root = BENCH_DIR / "fsharp"
    if not root.exists():
        sys.exit("dotnet/fsharp not cloned yet - run ./scripts/bench.py once first")
    valid, syntax, typeonly = [], [], []
    for p in sorted(root.rglob("*.fs")):
        if ".git" in p.parts:
            continue
        rel = str(p.relative_to(BENCH_DIR))
        deliberate = p.name.startswith("E_") or p.name.startswith("neg")
        if not deliberate:
            valid.append(rel)
            continue
        try:
            ids = set(EXPECTS_RE.findall(p.read_text("utf8", "replace")))
        except OSError:
            continue
        if ids & SYNTAX_DIAGNOSTICS:
            syntax.append(rel)
        elif ids:
            typeonly.append(rel)
    SCORE_DIR.mkdir(parents=True, exist_ok=True)
    for name, rows, note in [
        ("corpus-valid.txt", valid, "valid F# from dotnet/fsharp (coverage axis)"),
        ("corpus-syntax-error.txt", syntax, "expect a SYNTAX diagnostic (rejection recall)"),
        ("corpus-type-error.txt", typeonly, "expect only TYPE/name diagnostics - a correct parser ACCEPTS these"),
    ]:
        (SCORE_DIR / name).write_text(
            f"# {note}\n# frozen from the SHA pinned in scripts/bench-manifest.txt\n"
            + "\n".join(rows) + "\n")
        print(f"  {name}: {len(rows)}")


def sweep_clean(lang, paths):
    """(files, failing) over a list of bench-relative paths."""
    total = failing = 0
    for rel in paths:
        p = BENCH_DIR / rel
        try:
            data = p.read_bytes()
        except OSError:
            continue
        total += 1
        if not tsparse.is_clean(lang, data):
            failing += 1
    return total, failing


def axis_coverage_bench(lang):
    repos = read_manifest()
    files = list_files(repos)
    total = failing = 0
    for _, p in files:
        try:
            data = p.read_bytes()
        except OSError:
            continue
        total += 1
        if not tsparse.is_clean(lang, data):
            failing += 1
    return {"files": total, "failing": failing,
            "clean_pct": round(100 * (total - failing) / max(total, 1), 2)}


def axis_degeneracy(lang):
    wanted = load_keywords()
    repos = read_manifest()
    sites = 0
    bad_files = 0
    for _, p in list_files(repos):
        try:
            data = p.read_bytes()
        except OSError:
            continue
        dirty, hits = tsparse.identifier_texts(lang, data, wanted)
        if dirty or not hits:
            continue
        sites += len(hits)
        bad_files += 1
    return {"sites": sites, "files": bad_files}


def axis_highlight():
    q = (REPO / "queries" / "highlights.scm").read_text()
    captures = set(re.findall(r"@([\w.]+)", q))
    asserted = set()
    for f in (REPO / "test" / "highlight").glob("*"):
        for m in re.finditer(r"(?:\^|<-)\s*([\w.]+)", f.read_text()):
            asserted.add(m.group(1))
    covered = captures & asserted
    return {"captures": len(captures), "asserted": len(covered),
            "coverage_pct": round(100 * len(covered) / max(len(captures), 1), 2),
            "uncovered": sorted(captures - asserted)[:20]}


def score(lang, axes):
    out = {}
    if "coverage" in axes:
        out["coverage_bench"] = axis_coverage_bench(lang)
        valid = read_list("corpus-valid.txt")
        if valid:
            t, f = sweep_clean(lang, valid)
            out["coverage_dotnet_valid"] = {
                "files": t, "failing": f,
                "clean_pct": round(100 * (t - f) / max(t, 1), 2)}
    if "rejection" in axes:
        syn = read_list("corpus-syntax-error.txt")
        typ = read_list("corpus-type-error.txt")
        if syn:
            t, f = sweep_clean(lang, syn)
            out["rejection_recall"] = {
                "files": t, "flagged": f,
                "recall_pct": round(100 * f / max(t, 1), 2)}
        if typ:
            t, f = sweep_clean(lang, typ)
            out["rejection_false_positive"] = {
                "files": t, "flagged": f,
                "fp_pct": round(100 * f / max(t, 1), 2)}
    if "degeneracy" in axes:
        out["degeneracy"] = axis_degeneracy(lang)
    if "highlight" in axes:
        out["highlight"] = axis_highlight()
    return out


def render(ours, theirs=None):
    def cell(d, *keys):
        for k in keys:
            if d is None:
                return "-"
            d = d.get(k) if isinstance(d, dict) else None
            if d is None:
                return "-"
        return d

    rows = [
        ("coverage: bench corpus clean %", ("coverage_bench", "clean_pct"), "higher"),
        ("coverage: dotnet/fsharp valid clean %", ("coverage_dotnet_valid", "clean_pct"), "higher"),
        ("rejection: syntax-error recall %", ("rejection_recall", "recall_pct"), "higher"),
        ("rejection: false-positive %", ("rejection_false_positive", "fp_pct"), "lower"),
        ("degeneracy: keyword-as-identifier sites", ("degeneracy", "sites"), "lower"),
        ("highlight: capture coverage % (ours only)", ("highlight", "coverage_pct"), "higher"),
    ]
    w = max(len(r[0]) for r in rows)
    head = f"  {'axis'.ljust(w)}  {'ours':>10}"
    if theirs is not None:
        head += f"  {'other':>10}"
    head += "   better"
    print(head)
    print("  " + "-" * (len(head) - 2))
    for label, keys, better in rows:
        line = f"  {label.ljust(w)}  {str(cell(ours, *keys)):>10}"
        if theirs is not None:
            line += f"  {str(cell(theirs, *keys)):>10}"
        line += f"   {better}"
        print(line)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--parser", default=None, help="path to our .so (default parser.so)")
    ap.add_argument("--vs", default=None, help="path to another grammar's .so")
    ap.add_argument("--axes", default="all",
                    help="comma list: coverage,rejection,degeneracy,highlight")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--compare", action="store_true",
                    help="gate against test/score/baseline.json")
    ap.add_argument("--update-baseline", action="store_true")
    ap.add_argument("--regen-corpora", action="store_true")
    args = ap.parse_args()

    if args.regen_corpora:
        ensure_clones(read_manifest())
        regen_corpora()
        return

    axes = ({"coverage", "rejection", "degeneracy", "highlight"}
            if args.axes == "all" else set(args.axes.split(",")))

    tsparse.self_test(args.parser)
    ensure_clones(read_manifest())

    ours = score(tsparse.load(args.parser), axes)
    # The highlight axis reads OUR queries and OUR assertions, so it is a
    # property of this repo, not of the parser under test. Never report it in
    # the comparison column.
    theirs = (score(tsparse.load(args.vs), axes - {"highlight"})
              if args.vs else None)

    if args.json:
        print(json.dumps({"ours": ours, "other": theirs}, indent=2))
    else:
        render(ours, theirs)

    if args.update_baseline:
        SCORE_DIR.mkdir(parents=True, exist_ok=True)
        BASELINE.write_text(json.dumps(ours, indent=2) + "\n")
        print(f"\nbaseline written: {BASELINE.relative_to(REPO)}")
        return

    if args.compare:
        if not BASELINE.exists():
            sys.exit("no baseline - run --update-baseline first")
        base = json.loads(BASELINE.read_text())
        breaches = []

        def chk(path, better, tol=0.0):
            a, b = base, ours
            for k in path:
                a = (a or {}).get(k)
                b = (b or {}).get(k)
            if a is None or b is None:
                return
            if better == "higher" and b < a - tol:
                breaches.append(f"{'.'.join(path)}: {a} -> {b}")
            if better == "lower" and b > a + tol:
                breaches.append(f"{'.'.join(path)}: {a} -> {b}")

        chk(("coverage_bench", "clean_pct"), "higher")
        chk(("coverage_dotnet_valid", "clean_pct"), "higher", 0.05)
        chk(("rejection_recall", "recall_pct"), "higher")
        chk(("rejection_false_positive", "fp_pct"), "lower", 0.3)
        chk(("degeneracy", "sites"), "lower")
        chk(("highlight", "coverage_pct"), "higher")
        if breaches:
            print("\nGATE FAILED:")
            for b in breaches:
                print("  " + b)
            sys.exit(1)
        print("\nno regressions ✓")


if __name__ == "__main__":
    main()
