/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 19
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_open = 2,
  anon_sym_type = 3,
  anon_sym_DOT = 4,
  sym__int = 5,
  sym__hex = 6,
  sym__oct = 7,
  sym__bin = 8,
  sym__int_suffix = 9,
  sym__float_suffix = 10,
  aux_sym_float_literal_token1 = 11,
  aux_sym_float_literal_token2 = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  sym_unit = 15,
  sym_null_literal = 16,
  sym_line_comment = 17,
  sym_xml_doc_comment = 18,
  anon_sym_LPAREN_STAR = 19,
  aux_sym_block_comment_token1 = 20,
  aux_sym_block_comment_token2 = 21,
  aux_sym_block_comment_token3 = 22,
  anon_sym_STAR_RPAREN = 23,
  anon_sym_LPAREN_STAR_STAR = 24,
  sym_source_file = 25,
  sym_import_decl = 26,
  sym__token = 27,
  sym_long_identifier = 28,
  sym_int_literal = 29,
  sym_float_literal = 30,
  sym_bool_literal = 31,
  sym_block_comment = 32,
  sym_block_doc_comment = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_long_identifier_repeat1 = 35,
  aux_sym_block_comment_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_open] = "open",
  [anon_sym_type] = "type",
  [anon_sym_DOT] = ".",
  [sym__int] = "_int",
  [sym__hex] = "_hex",
  [sym__oct] = "_oct",
  [sym__bin] = "_bin",
  [sym__int_suffix] = "_int_suffix",
  [sym__float_suffix] = "_float_suffix",
  [aux_sym_float_literal_token1] = "float_literal_token1",
  [aux_sym_float_literal_token2] = "float_literal_token2",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_unit] = "unit",
  [sym_null_literal] = "null_literal",
  [sym_line_comment] = "line_comment",
  [sym_xml_doc_comment] = "xml_doc_comment",
  [anon_sym_LPAREN_STAR] = "(*",
  [aux_sym_block_comment_token1] = "block_comment_token1",
  [aux_sym_block_comment_token2] = "block_comment_token2",
  [aux_sym_block_comment_token3] = "block_comment_token3",
  [anon_sym_STAR_RPAREN] = "*)",
  [anon_sym_LPAREN_STAR_STAR] = "(**",
  [sym_source_file] = "source_file",
  [sym_import_decl] = "import_decl",
  [sym__token] = "_token",
  [sym_long_identifier] = "long_identifier",
  [sym_int_literal] = "int_literal",
  [sym_float_literal] = "float_literal",
  [sym_bool_literal] = "bool_literal",
  [sym_block_comment] = "block_comment",
  [sym_block_doc_comment] = "block_doc_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_long_identifier_repeat1] = "long_identifier_repeat1",
  [aux_sym_block_comment_repeat1] = "block_comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_open] = anon_sym_open,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym__int] = sym__int,
  [sym__hex] = sym__hex,
  [sym__oct] = sym__oct,
  [sym__bin] = sym__bin,
  [sym__int_suffix] = sym__int_suffix,
  [sym__float_suffix] = sym__float_suffix,
  [aux_sym_float_literal_token1] = aux_sym_float_literal_token1,
  [aux_sym_float_literal_token2] = aux_sym_float_literal_token2,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_unit] = sym_unit,
  [sym_null_literal] = sym_null_literal,
  [sym_line_comment] = sym_line_comment,
  [sym_xml_doc_comment] = sym_xml_doc_comment,
  [anon_sym_LPAREN_STAR] = anon_sym_LPAREN_STAR,
  [aux_sym_block_comment_token1] = aux_sym_block_comment_token1,
  [aux_sym_block_comment_token2] = aux_sym_block_comment_token2,
  [aux_sym_block_comment_token3] = aux_sym_block_comment_token3,
  [anon_sym_STAR_RPAREN] = anon_sym_STAR_RPAREN,
  [anon_sym_LPAREN_STAR_STAR] = anon_sym_LPAREN_STAR_STAR,
  [sym_source_file] = sym_source_file,
  [sym_import_decl] = sym_import_decl,
  [sym__token] = sym__token,
  [sym_long_identifier] = sym_long_identifier,
  [sym_int_literal] = sym_int_literal,
  [sym_float_literal] = sym_float_literal,
  [sym_bool_literal] = sym_bool_literal,
  [sym_block_comment] = sym_block_comment,
  [sym_block_doc_comment] = sym_block_doc_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_long_identifier_repeat1] = aux_sym_long_identifier_repeat1,
  [aux_sym_block_comment_repeat1] = aux_sym_block_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_open] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym__int] = {
    .visible = false,
    .named = true,
  },
  [sym__hex] = {
    .visible = false,
    .named = true,
  },
  [sym__oct] = {
    .visible = false,
    .named = true,
  },
  [sym__bin] = {
    .visible = false,
    .named = true,
  },
  [sym__int_suffix] = {
    .visible = false,
    .named = true,
  },
  [sym__float_suffix] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_float_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_null_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_comment_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_import_decl] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_long_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_int_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_long_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 20,
  [25] = 23,
  [26] = 19,
  [27] = 21,
  [28] = 23,
  [29] = 19,
  [30] = 30,
  [31] = 16,
  [32] = 18,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 17,
  [38] = 16,
  [39] = 18,
  [40] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '(', 3,
        '*', 4,
        '.', 20,
        '/', 6,
        '0', 21,
        'F', 27,
        'M', 27,
        'f', 27,
        'm', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(31);
      if (lookahead == '*') ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(31);
      if (lookahead == '*') ADVANCE(35);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(41);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(35);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(26);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(25);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 14:
      if (eof) ADVANCE(18);
      if (lookahead == '(') ADVANCE(3);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 15:
      if (eof) ADVANCE(18);
      if (lookahead == '(') ADVANCE(2);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 16:
      if (eof) ADVANCE(18);
      if (lookahead == '(') ADVANCE(2);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(21);
      if (lookahead == 'F' ||
          lookahead == 'M' ||
          lookahead == 'f' ||
          lookahead == 'm') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '(') ADVANCE(2);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__int);
      ADVANCE_MAP(
        '.', 28,
        '_', 23,
        'B', 9,
        'b', 9,
        'E', 7,
        'e', 7,
        'O', 10,
        'o', 10,
        'X', 13,
        'x', 13,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__int);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == '_') ADVANCE(23);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__int);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__hex);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__oct);
      if (('0' <= lookahead && lookahead <= '7') ||
          lookahead == '_') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__bin);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__float_suffix);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_float_literal_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_float_literal_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_float_literal_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_unit);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_xml_doc_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR);
      if (lookahead == '*') ADVANCE(42);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      if (lookahead == '/') ADVANCE(32);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      if (lookahead == '/') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != '*') ADVANCE(36);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_block_comment_token2);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_block_comment_token3);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_STAR_RPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LPAREN_STAR_STAR);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'U') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 'o') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == 'F' ||
          lookahead == 'I' ||
          lookahead == 'L' ||
          lookahead == 'M' ||
          lookahead == 'l' ||
          lookahead == 'm' ||
          lookahead == 's' ||
          lookahead == 'y') ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym__int_suffix);
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym__int_suffix);
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(12);
      if (lookahead == 'y') ADVANCE(13);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym__int_suffix);
      if (lookahead == 'L' ||
          lookahead == 'l' ||
          lookahead == 'n' ||
          lookahead == 's' ||
          lookahead == 'y') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym__int_suffix);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_null_literal);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_open);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 15},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 15},
  [12] = {.lex_state = 15},
  [13] = {.lex_state = 15},
  [14] = {.lex_state = 15},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 15},
  [17] = {.lex_state = 15},
  [18] = {.lex_state = 15},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 15},
  [35] = {.lex_state = 15},
  [36] = {.lex_state = 0},
  [37] = {(TSStateId)(-1),},
  [38] = {(TSStateId)(-1),},
  [39] = {(TSStateId)(-1),},
  [40] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_block_comment] = STATE(0),
    [sym_block_doc_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_open] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__int] = ACTIONS(1),
    [sym__hex] = ACTIONS(1),
    [sym__oct] = ACTIONS(1),
    [sym__bin] = ACTIONS(1),
    [sym__int_suffix] = ACTIONS(1),
    [sym__float_suffix] = ACTIONS(1),
    [aux_sym_float_literal_token1] = ACTIONS(1),
    [aux_sym_float_literal_token2] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_unit] = ACTIONS(1),
    [sym_null_literal] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_xml_doc_comment] = ACTIONS(5),
    [anon_sym_LPAREN_STAR] = ACTIONS(7),
    [aux_sym_block_comment_token2] = ACTIONS(1),
    [aux_sym_block_comment_token3] = ACTIONS(1),
    [anon_sym_STAR_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(9),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(36),
    [sym_import_decl] = STATE(2),
    [sym__token] = STATE(2),
    [sym_long_identifier] = STATE(2),
    [sym_int_literal] = STATE(2),
    [sym_float_literal] = STATE(2),
    [sym_bool_literal] = STATE(2),
    [sym_block_comment] = STATE(1),
    [sym_block_doc_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_open] = ACTIONS(15),
    [sym__int] = ACTIONS(17),
    [sym__hex] = ACTIONS(19),
    [sym__oct] = ACTIONS(19),
    [sym__bin] = ACTIONS(19),
    [aux_sym_float_literal_token1] = ACTIONS(21),
    [aux_sym_float_literal_token2] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_unit] = ACTIONS(25),
    [sym_null_literal] = ACTIONS(27),
    [sym_line_comment] = ACTIONS(27),
    [sym_xml_doc_comment] = ACTIONS(25),
    [anon_sym_LPAREN_STAR] = ACTIONS(29),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(31),
  },
  [STATE(2)] = {
    [sym_import_decl] = STATE(3),
    [sym__token] = STATE(3),
    [sym_long_identifier] = STATE(3),
    [sym_int_literal] = STATE(3),
    [sym_float_literal] = STATE(3),
    [sym_bool_literal] = STATE(3),
    [sym_block_comment] = STATE(2),
    [sym_block_doc_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_open] = ACTIONS(15),
    [sym__int] = ACTIONS(17),
    [sym__hex] = ACTIONS(19),
    [sym__oct] = ACTIONS(19),
    [sym__bin] = ACTIONS(19),
    [aux_sym_float_literal_token1] = ACTIONS(21),
    [aux_sym_float_literal_token2] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_unit] = ACTIONS(35),
    [sym_null_literal] = ACTIONS(37),
    [sym_line_comment] = ACTIONS(37),
    [sym_xml_doc_comment] = ACTIONS(35),
    [anon_sym_LPAREN_STAR] = ACTIONS(29),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(31),
  },
  [STATE(3)] = {
    [sym_import_decl] = STATE(3),
    [sym__token] = STATE(3),
    [sym_long_identifier] = STATE(3),
    [sym_int_literal] = STATE(3),
    [sym_float_literal] = STATE(3),
    [sym_bool_literal] = STATE(3),
    [sym_block_comment] = STATE(3),
    [sym_block_doc_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_identifier] = ACTIONS(41),
    [anon_sym_open] = ACTIONS(44),
    [sym__int] = ACTIONS(47),
    [sym__hex] = ACTIONS(50),
    [sym__oct] = ACTIONS(50),
    [sym__bin] = ACTIONS(50),
    [aux_sym_float_literal_token1] = ACTIONS(53),
    [aux_sym_float_literal_token2] = ACTIONS(53),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_unit] = ACTIONS(59),
    [sym_null_literal] = ACTIONS(62),
    [sym_line_comment] = ACTIONS(62),
    [sym_xml_doc_comment] = ACTIONS(59),
    [anon_sym_LPAREN_STAR] = ACTIONS(65),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(68),
  },
  [STATE(4)] = {
    [sym_block_comment] = STATE(4),
    [sym_block_doc_comment] = STATE(4),
    [aux_sym_long_identifier_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(71),
    [sym_identifier] = ACTIONS(73),
    [anon_sym_open] = ACTIONS(73),
    [anon_sym_DOT] = ACTIONS(75),
    [sym__int] = ACTIONS(73),
    [sym__hex] = ACTIONS(71),
    [sym__oct] = ACTIONS(71),
    [sym__bin] = ACTIONS(71),
    [aux_sym_float_literal_token1] = ACTIONS(71),
    [aux_sym_float_literal_token2] = ACTIONS(71),
    [anon_sym_true] = ACTIONS(73),
    [anon_sym_false] = ACTIONS(73),
    [sym_unit] = ACTIONS(71),
    [sym_null_literal] = ACTIONS(73),
    [sym_line_comment] = ACTIONS(73),
    [sym_xml_doc_comment] = ACTIONS(71),
    [anon_sym_LPAREN_STAR] = ACTIONS(73),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(71),
  },
  [STATE(5)] = {
    [sym_block_comment] = STATE(5),
    [sym_block_doc_comment] = STATE(5),
    [aux_sym_long_identifier_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(77),
    [sym_identifier] = ACTIONS(79),
    [anon_sym_open] = ACTIONS(79),
    [anon_sym_DOT] = ACTIONS(75),
    [sym__int] = ACTIONS(79),
    [sym__hex] = ACTIONS(77),
    [sym__oct] = ACTIONS(77),
    [sym__bin] = ACTIONS(77),
    [aux_sym_float_literal_token1] = ACTIONS(77),
    [aux_sym_float_literal_token2] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(79),
    [anon_sym_false] = ACTIONS(79),
    [sym_unit] = ACTIONS(77),
    [sym_null_literal] = ACTIONS(79),
    [sym_line_comment] = ACTIONS(79),
    [sym_xml_doc_comment] = ACTIONS(77),
    [anon_sym_LPAREN_STAR] = ACTIONS(79),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(77),
  },
  [STATE(6)] = {
    [sym_block_comment] = STATE(6),
    [sym_block_doc_comment] = STATE(6),
    [aux_sym_long_identifier_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_identifier] = ACTIONS(83),
    [anon_sym_open] = ACTIONS(83),
    [anon_sym_DOT] = ACTIONS(85),
    [sym__int] = ACTIONS(83),
    [sym__hex] = ACTIONS(81),
    [sym__oct] = ACTIONS(81),
    [sym__bin] = ACTIONS(81),
    [aux_sym_float_literal_token1] = ACTIONS(81),
    [aux_sym_float_literal_token2] = ACTIONS(81),
    [anon_sym_true] = ACTIONS(83),
    [anon_sym_false] = ACTIONS(83),
    [sym_unit] = ACTIONS(81),
    [sym_null_literal] = ACTIONS(83),
    [sym_line_comment] = ACTIONS(83),
    [sym_xml_doc_comment] = ACTIONS(81),
    [anon_sym_LPAREN_STAR] = ACTIONS(83),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(81),
  },
  [STATE(7)] = {
    [sym_block_comment] = STATE(7),
    [sym_block_doc_comment] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(88),
    [sym_identifier] = ACTIONS(90),
    [anon_sym_open] = ACTIONS(90),
    [sym__int] = ACTIONS(90),
    [sym__hex] = ACTIONS(88),
    [sym__oct] = ACTIONS(88),
    [sym__bin] = ACTIONS(88),
    [sym__float_suffix] = ACTIONS(92),
    [aux_sym_float_literal_token1] = ACTIONS(88),
    [aux_sym_float_literal_token2] = ACTIONS(88),
    [anon_sym_true] = ACTIONS(90),
    [anon_sym_false] = ACTIONS(90),
    [sym_unit] = ACTIONS(88),
    [sym_null_literal] = ACTIONS(90),
    [sym_line_comment] = ACTIONS(90),
    [sym_xml_doc_comment] = ACTIONS(88),
    [anon_sym_LPAREN_STAR] = ACTIONS(90),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(88),
  },
  [STATE(8)] = {
    [sym_block_comment] = STATE(8),
    [sym_block_doc_comment] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(94),
    [sym_identifier] = ACTIONS(96),
    [anon_sym_open] = ACTIONS(96),
    [sym__int] = ACTIONS(96),
    [sym__hex] = ACTIONS(94),
    [sym__oct] = ACTIONS(94),
    [sym__bin] = ACTIONS(94),
    [sym__int_suffix] = ACTIONS(98),
    [aux_sym_float_literal_token1] = ACTIONS(94),
    [aux_sym_float_literal_token2] = ACTIONS(94),
    [anon_sym_true] = ACTIONS(96),
    [anon_sym_false] = ACTIONS(96),
    [sym_unit] = ACTIONS(94),
    [sym_null_literal] = ACTIONS(96),
    [sym_line_comment] = ACTIONS(96),
    [sym_xml_doc_comment] = ACTIONS(94),
    [anon_sym_LPAREN_STAR] = ACTIONS(96),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(94),
  },
  [STATE(9)] = {
    [sym_block_comment] = STATE(9),
    [sym_block_doc_comment] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_identifier] = ACTIONS(83),
    [anon_sym_open] = ACTIONS(83),
    [anon_sym_DOT] = ACTIONS(81),
    [sym__int] = ACTIONS(83),
    [sym__hex] = ACTIONS(81),
    [sym__oct] = ACTIONS(81),
    [sym__bin] = ACTIONS(81),
    [aux_sym_float_literal_token1] = ACTIONS(81),
    [aux_sym_float_literal_token2] = ACTIONS(81),
    [anon_sym_true] = ACTIONS(83),
    [anon_sym_false] = ACTIONS(83),
    [sym_unit] = ACTIONS(81),
    [sym_null_literal] = ACTIONS(83),
    [sym_line_comment] = ACTIONS(83),
    [sym_xml_doc_comment] = ACTIONS(81),
    [anon_sym_LPAREN_STAR] = ACTIONS(83),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(81),
  },
  [STATE(10)] = {
    [sym_block_comment] = STATE(10),
    [sym_block_doc_comment] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(100),
    [sym_identifier] = ACTIONS(102),
    [anon_sym_open] = ACTIONS(102),
    [sym__int] = ACTIONS(102),
    [sym__hex] = ACTIONS(100),
    [sym__oct] = ACTIONS(100),
    [sym__bin] = ACTIONS(100),
    [aux_sym_float_literal_token1] = ACTIONS(100),
    [aux_sym_float_literal_token2] = ACTIONS(100),
    [anon_sym_true] = ACTIONS(102),
    [anon_sym_false] = ACTIONS(102),
    [sym_unit] = ACTIONS(100),
    [sym_null_literal] = ACTIONS(102),
    [sym_line_comment] = ACTIONS(102),
    [sym_xml_doc_comment] = ACTIONS(100),
    [anon_sym_LPAREN_STAR] = ACTIONS(102),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(100),
  },
  [STATE(11)] = {
    [sym_block_comment] = STATE(11),
    [sym_block_doc_comment] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(104),
    [sym_identifier] = ACTIONS(106),
    [anon_sym_open] = ACTIONS(106),
    [sym__int] = ACTIONS(106),
    [sym__hex] = ACTIONS(104),
    [sym__oct] = ACTIONS(104),
    [sym__bin] = ACTIONS(104),
    [aux_sym_float_literal_token1] = ACTIONS(104),
    [aux_sym_float_literal_token2] = ACTIONS(104),
    [anon_sym_true] = ACTIONS(106),
    [anon_sym_false] = ACTIONS(106),
    [sym_unit] = ACTIONS(104),
    [sym_null_literal] = ACTIONS(106),
    [sym_line_comment] = ACTIONS(106),
    [sym_xml_doc_comment] = ACTIONS(104),
    [anon_sym_LPAREN_STAR] = ACTIONS(106),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(104),
  },
  [STATE(12)] = {
    [sym_block_comment] = STATE(12),
    [sym_block_doc_comment] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(108),
    [sym_identifier] = ACTIONS(110),
    [anon_sym_open] = ACTIONS(110),
    [sym__int] = ACTIONS(110),
    [sym__hex] = ACTIONS(108),
    [sym__oct] = ACTIONS(108),
    [sym__bin] = ACTIONS(108),
    [aux_sym_float_literal_token1] = ACTIONS(108),
    [aux_sym_float_literal_token2] = ACTIONS(108),
    [anon_sym_true] = ACTIONS(110),
    [anon_sym_false] = ACTIONS(110),
    [sym_unit] = ACTIONS(108),
    [sym_null_literal] = ACTIONS(110),
    [sym_line_comment] = ACTIONS(110),
    [sym_xml_doc_comment] = ACTIONS(108),
    [anon_sym_LPAREN_STAR] = ACTIONS(110),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(108),
  },
  [STATE(13)] = {
    [sym_block_comment] = STATE(13),
    [sym_block_doc_comment] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_identifier] = ACTIONS(114),
    [anon_sym_open] = ACTIONS(114),
    [sym__int] = ACTIONS(114),
    [sym__hex] = ACTIONS(112),
    [sym__oct] = ACTIONS(112),
    [sym__bin] = ACTIONS(112),
    [aux_sym_float_literal_token1] = ACTIONS(112),
    [aux_sym_float_literal_token2] = ACTIONS(112),
    [anon_sym_true] = ACTIONS(114),
    [anon_sym_false] = ACTIONS(114),
    [sym_unit] = ACTIONS(112),
    [sym_null_literal] = ACTIONS(114),
    [sym_line_comment] = ACTIONS(114),
    [sym_xml_doc_comment] = ACTIONS(112),
    [anon_sym_LPAREN_STAR] = ACTIONS(114),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(112),
  },
  [STATE(14)] = {
    [sym_block_comment] = STATE(14),
    [sym_block_doc_comment] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(116),
    [sym_identifier] = ACTIONS(118),
    [anon_sym_open] = ACTIONS(118),
    [sym__int] = ACTIONS(118),
    [sym__hex] = ACTIONS(116),
    [sym__oct] = ACTIONS(116),
    [sym__bin] = ACTIONS(116),
    [aux_sym_float_literal_token1] = ACTIONS(116),
    [aux_sym_float_literal_token2] = ACTIONS(116),
    [anon_sym_true] = ACTIONS(118),
    [anon_sym_false] = ACTIONS(118),
    [sym_unit] = ACTIONS(116),
    [sym_null_literal] = ACTIONS(118),
    [sym_line_comment] = ACTIONS(118),
    [sym_xml_doc_comment] = ACTIONS(116),
    [anon_sym_LPAREN_STAR] = ACTIONS(118),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(116),
  },
  [STATE(15)] = {
    [sym_block_comment] = STATE(15),
    [sym_block_doc_comment] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(120),
    [sym_identifier] = ACTIONS(122),
    [anon_sym_open] = ACTIONS(122),
    [sym__int] = ACTIONS(122),
    [sym__hex] = ACTIONS(120),
    [sym__oct] = ACTIONS(120),
    [sym__bin] = ACTIONS(120),
    [aux_sym_float_literal_token1] = ACTIONS(120),
    [aux_sym_float_literal_token2] = ACTIONS(120),
    [anon_sym_true] = ACTIONS(122),
    [anon_sym_false] = ACTIONS(122),
    [sym_unit] = ACTIONS(120),
    [sym_null_literal] = ACTIONS(122),
    [sym_line_comment] = ACTIONS(122),
    [sym_xml_doc_comment] = ACTIONS(120),
    [anon_sym_LPAREN_STAR] = ACTIONS(122),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(120),
  },
  [STATE(16)] = {
    [sym_block_comment] = STATE(16),
    [sym_block_doc_comment] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(124),
    [sym_identifier] = ACTIONS(126),
    [anon_sym_open] = ACTIONS(126),
    [sym__int] = ACTIONS(126),
    [sym__hex] = ACTIONS(124),
    [sym__oct] = ACTIONS(124),
    [sym__bin] = ACTIONS(124),
    [aux_sym_float_literal_token1] = ACTIONS(124),
    [aux_sym_float_literal_token2] = ACTIONS(124),
    [anon_sym_true] = ACTIONS(126),
    [anon_sym_false] = ACTIONS(126),
    [sym_unit] = ACTIONS(124),
    [sym_null_literal] = ACTIONS(126),
    [sym_line_comment] = ACTIONS(126),
    [sym_xml_doc_comment] = ACTIONS(124),
    [anon_sym_LPAREN_STAR] = ACTIONS(126),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(124),
  },
  [STATE(17)] = {
    [sym_block_comment] = STATE(17),
    [sym_block_doc_comment] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(128),
    [sym_identifier] = ACTIONS(130),
    [anon_sym_open] = ACTIONS(130),
    [sym__int] = ACTIONS(130),
    [sym__hex] = ACTIONS(128),
    [sym__oct] = ACTIONS(128),
    [sym__bin] = ACTIONS(128),
    [aux_sym_float_literal_token1] = ACTIONS(128),
    [aux_sym_float_literal_token2] = ACTIONS(128),
    [anon_sym_true] = ACTIONS(130),
    [anon_sym_false] = ACTIONS(130),
    [sym_unit] = ACTIONS(128),
    [sym_null_literal] = ACTIONS(130),
    [sym_line_comment] = ACTIONS(130),
    [sym_xml_doc_comment] = ACTIONS(128),
    [anon_sym_LPAREN_STAR] = ACTIONS(130),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(128),
  },
  [STATE(18)] = {
    [sym_block_comment] = STATE(18),
    [sym_block_doc_comment] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(132),
    [sym_identifier] = ACTIONS(134),
    [anon_sym_open] = ACTIONS(134),
    [sym__int] = ACTIONS(134),
    [sym__hex] = ACTIONS(132),
    [sym__oct] = ACTIONS(132),
    [sym__bin] = ACTIONS(132),
    [aux_sym_float_literal_token1] = ACTIONS(132),
    [aux_sym_float_literal_token2] = ACTIONS(132),
    [anon_sym_true] = ACTIONS(134),
    [anon_sym_false] = ACTIONS(134),
    [sym_unit] = ACTIONS(132),
    [sym_null_literal] = ACTIONS(134),
    [sym_line_comment] = ACTIONS(134),
    [sym_xml_doc_comment] = ACTIONS(132),
    [anon_sym_LPAREN_STAR] = ACTIONS(134),
    [anon_sym_LPAREN_STAR_STAR] = ACTIONS(132),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(136), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(140), 1,
      anon_sym_STAR_RPAREN,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    STATE(22), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(19), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(138), 3,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
  [26] = 7,
    ACTIONS(136), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(144), 1,
      anon_sym_STAR_RPAREN,
    STATE(21), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(20), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(138), 3,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
  [52] = 7,
    ACTIONS(136), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(146), 1,
      anon_sym_STAR_RPAREN,
    STATE(22), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(21), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(138), 3,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
  [78] = 6,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(148), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(154), 1,
      anon_sym_STAR_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    ACTIONS(151), 3,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
    STATE(22), 3,
      sym_block_comment,
      sym_block_doc_comment,
      aux_sym_block_comment_repeat1,
  [102] = 7,
    ACTIONS(136), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(156), 1,
      anon_sym_STAR_RPAREN,
    STATE(19), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(23), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(138), 3,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
  [128] = 7,
    ACTIONS(136), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(158), 1,
      anon_sym_STAR_RPAREN,
    STATE(27), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(24), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(138), 3,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
  [154] = 7,
    ACTIONS(136), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(160), 1,
      anon_sym_STAR_RPAREN,
    STATE(26), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(25), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(138), 3,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
  [180] = 7,
    ACTIONS(136), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(162), 1,
      anon_sym_STAR_RPAREN,
    STATE(22), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(26), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(138), 3,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
  [206] = 7,
    ACTIONS(136), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(164), 1,
      anon_sym_STAR_RPAREN,
    STATE(22), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(27), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(138), 3,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
  [232] = 7,
    ACTIONS(136), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(166), 1,
      anon_sym_STAR_RPAREN,
    STATE(29), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(28), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(138), 3,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
  [258] = 7,
    ACTIONS(136), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(168), 1,
      anon_sym_STAR_RPAREN,
    STATE(22), 1,
      aux_sym_block_comment_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(29), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(138), 3,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
  [284] = 4,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(30), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(170), 5,
      anon_sym_LPAREN_STAR,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
      anon_sym_STAR_RPAREN,
  [303] = 4,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(31), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(126), 5,
      anon_sym_LPAREN_STAR,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
      anon_sym_STAR_RPAREN,
  [322] = 4,
    ACTIONS(142), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_xml_doc_comment,
    STATE(32), 2,
      sym_block_comment,
      sym_block_doc_comment,
    ACTIONS(134), 5,
      anon_sym_LPAREN_STAR,
      aux_sym_block_comment_token1,
      aux_sym_block_comment_token2,
      aux_sym_block_comment_token3,
      anon_sym_STAR_RPAREN,
  [341] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_xml_doc_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(172), 1,
      anon_sym_type,
    STATE(13), 1,
      sym_long_identifier,
    STATE(33), 2,
      sym_block_comment,
      sym_block_doc_comment,
  [367] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_xml_doc_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(174), 1,
      sym_identifier,
    STATE(14), 1,
      sym_long_identifier,
    STATE(34), 2,
      sym_block_comment,
      sym_block_doc_comment,
  [390] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_xml_doc_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(35), 2,
      sym_block_comment,
      sym_block_doc_comment,
  [410] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_xml_doc_comment,
    ACTIONS(7), 1,
      anon_sym_LPAREN_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN_STAR_STAR,
    ACTIONS(178), 1,
      ts_builtin_sym_end,
    STATE(36), 2,
      sym_block_comment,
      sym_block_doc_comment,
  [430] = 1,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
  [434] = 1,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
  [438] = 1,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
  [442] = 1,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(19)] = 0,
  [SMALL_STATE(20)] = 26,
  [SMALL_STATE(21)] = 52,
  [SMALL_STATE(22)] = 78,
  [SMALL_STATE(23)] = 102,
  [SMALL_STATE(24)] = 128,
  [SMALL_STATE(25)] = 154,
  [SMALL_STATE(26)] = 180,
  [SMALL_STATE(27)] = 206,
  [SMALL_STATE(28)] = 232,
  [SMALL_STATE(29)] = 258,
  [SMALL_STATE(30)] = 284,
  [SMALL_STATE(31)] = 303,
  [SMALL_STATE(32)] = 322,
  [SMALL_STATE(33)] = 341,
  [SMALL_STATE(34)] = 367,
  [SMALL_STATE(35)] = 390,
  [SMALL_STATE(36)] = 410,
  [SMALL_STATE(37)] = 430,
  [SMALL_STATE(38)] = 434,
  [SMALL_STATE(39)] = 438,
  [SMALL_STATE(40)] = 442,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_long_identifier, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_long_identifier, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_long_identifier, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_long_identifier, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_long_identifier_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_long_identifier_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_long_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_literal, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_literal, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_literal, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int_literal, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_literal, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int_literal, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool_literal, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool_literal, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_literal, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_literal, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_decl, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_decl, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_decl, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_decl, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_doc_comment, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_doc_comment, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_doc_comment, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_doc_comment, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_comment, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_comment_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_comment_repeat1, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [178] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fsharp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fsharp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
